import Link from 'next/link';
import '../../global.css';
import Providers from "../components/providers"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <h1 className='text-3xl'>Example Onborda</h1>
          <nav className='flex gap-2 p-2 bg-slate-100'>
            <Link href={'/home'} >Home</Link>
            <Link href={'/about'} >About</Link>
          </nav>
          {children}
        </Providers>
        </body>
    </html>
  )
}
